keys:
  - &admin_otavio b7f7f218a0541d2a0bedbe8beb70fef3cdfc6e4f
  - &host_micro age1wnsj3p3w4yrw98v2tqup9jqe9w3r8gpcxh4nsh2828txpxx5xusqwcf5qg
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *host_micro
      pgp:
      - *admin_otavio
  - path_regex: secrets/admins/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *admin_otavio
