#!/bin/sh

# Directories which we intend to have included for every user
base=(
    zsh
)

# Normal user only
useronly=(
    aspell
    tmux
    git
    emacs
    i3wm
    misc
    topgrade
    x11
)

# run the stow command for the passed in directory ($2) in location $1
stowit() {
    usr=$1
    app=$2
    stow -D -t    ${usr} ${app}
    stow -v -R -t ${usr} ${app}
}

echo ""
echo "Stowing for user: $(whoami)"

git submodule update

# Common contents
for app in ${base[@]}; do
    stowit "${HOME}" $app
done

# User only contents
for app in ${useronly[@]}; do
    [[ "$(whoami)" != "root" ]] && stowit "${HOME}" $app
done

echo ""
echo "##### ALL DONE"
