#!/bin/sh

layer=$1

if [ -z "$layer" ]; then
	echo "Please set the machines to build."
	echo "e.g: $0 <layer name>"
	exit 1
fi

find ../sources/$layer/conf/machine  -maxdepth 1 -type f | sed 's,.*/,,g;s,.conf,,g'
