#!/bin/sh

project_name=$1
release=$2
yocto_env=$3

if [ -z $project_name ] || [ -z $release ]; then
    echo "Invalid usage. Please check if you're using this correctly:"
    cat <<EOF
$0 <project_name> <release>
EOF
    exit 1
fi

tmuxp_profile="$HOME/.tmuxp/$project_name-$release.yaml"
project_home="$HOME/src/oe/$project_name/$release"


if [ -e "$tmuxp_profile" ]; then
    echo "INFO: $tmuxp_profile already has been overridden."
fi

[ -n "$yocto_env" ] || yocto_env=20.04

cat > $tmuxp_profile << EOF
session_name: $(echo $project_name-$release | tr '.' '-')
start_directory: $project_home
windows:
- layout: even-horizontal
  shell_command_before: alias cd='HOME=$project_home cd'
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command: |
      yocto-env $yocto_env
      source setup-environment build
  - cd && touch .projectile && eval \$EDITOR
  - cd
  start_directory: $project_home
  window_name: build
EOF

mkdir -p $project_home

cat <<EOF
Project home create. Go there using:

cd $project_home
EOF

