#! /usr/bin/env bash

usage() {
    cat <<EOF
Yocto Project Environment helper

USAGE:

  yocto-env <version> [--skip-pull]

OPTIONS

  version           Environment version to use. This maps to Ubuntu releases
                    and currently it provides the 14.04, 16.04, 18.04,
                    20.04 and 22.04.
EOF
    exit 1
}

case "$1" in
    14.04*|16.04*|18.04*|20.04*|22.04*)
        version=$1
        ;;
    *)
        usage
        ;;
esac

USER=$(whoami)
IMAGE=ossystems/yocto-env:$version

case "$2" in
    --skip-pull)
        ;;
    "")
        docker pull $IMAGE
        ;;
    *)
        usage
        ;;
esac

DOCKER_EXTRA_ARGS=""

# ssh-agent support
[ -n "$SSH_AUTH_SOCK" ] && DOCKER_EXTRA_ARGS="$DOCKER_EXTRA_ARGS -v $SSH_AUTH_SOCK:/ssh-agent --env=SSH_AUTH_SOCK=/ssh-agent"

docker run \
       --rm \
       -t \
       -i \
       --privileged \
       --cap-add=NET_ADMIN \
       --device=/dev/kvm \
       --device=/dev/net/tun \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v /nix:/nix \
       -v ${HOME}:${HOME} \
       --env DISPLAY=$DISPLAY \
       --env=HOST_UID=$(id -u) \
       --env=HOST_GID=$(id -g) \
       --env=USER=$USER \
       --env=SHELL=$SHELL \
       --hostname yocto-env \
       $DOCKER_EXTRA_ARGS \
       $YOCTO_ENV_EXTRA_DOCKER_ARGS \
       -w $PWD \
       $IMAGE run
