SCONF_VERSION = "1"

DL_DIR = "/home/otavio/Downloads/yocto-downloads"
SSTATE_DIR = "/home/otavio/Downloads/sstate-cache"
BB_HASHSERVE_DB_DIR = "${SSTATE_DIR}"

OE_TERMINAL = "tmux-new-window"

BB_PRESSURE_MAX_CPU = "800"
