name: "CI"

on:
  pull_request:
    paths:
      - '**.nix'
      - 'flake.lock'
      - '.github/workflows/ci.yaml'
  push:
    branches: [ master ]
    paths:
      - '**.nix'
      - 'flake.lock'
      - '.github/workflows/ci.yaml'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: ossystems/nix-actions@v1
        with:
          install-nix: true
          flake-check: false
          build-hosts: false
          build-devshells: false
          build-attrs: matrix

  nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        homeConfiguration:
          - "otavio@generic-x86"
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: ossystems/nix-actions@v1
        with:
          install-nix: true
          flake-check: false
          build-hosts: false
          build-devshells: false
      - run: nix -L build ".#homeConfigurations.${{ matrix.homeConfiguration }}.activationPackage"
