name: "CI"

on:
  pull_request:
    paths:
      - '**.nix'
      - 'flake.lock'
  push:
    branches: [ master ]
    paths:
      - '**.nix'
      - 'flake.lock'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -euo pipefail

          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"

  nix-check:
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.*') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - run: nix build -L ".#${{ matrix.attr }}" --keep-going

  nixos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixosConfiguration:
          - micro
          - poirot
          - miss-marple
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.*') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - run: nix -L build ".#nixosConfigurations.${{ matrix.nixosConfiguration }}.config.system.build.toplevel"

  nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        homeConfiguration:
          - "otavio@generic-x86"
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.*') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - run: nix -L build ".#homeConfigurations.${{ matrix.homeConfiguration }}.activationPackage"
