name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: experimental-features = nix-command flakes repl-flake
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Print PR number
        run: echo Pull request number is ${{ steps.update.outputs.pull-request-number }}.
