msmtp:
    password: ENC[AES256_GCM,data:S76Cp1qc/EKXlqQBFBWPtw==,iv:o4qCg+qRHrcvM99Ijysr9o/qoUdq+9vbKWI7bi7zg0w=,tag:JazB1ButYEvnnxGpmenhvw==,type:str]
irssi-nickserv: ENC[AES256_GCM,data:sWxgDbtwHcQ54EholpOqQHDv8Oc=,iv:5imtFQK/ZlBnnar/waWArYWcXeHKlHSy2Vbs2opnJHM=,tag:P7ix7GdK/DIrlpCjLz7IIA==,type:str]
openapi: ENC[AES256_GCM,data:CDbTW7DFfEvgCUHnreAfEYs1nJnC3eGNe9CIb/78BzlEk8C99dB33HB7OOA42KlG7UoR,iv:rPsO3QetQPhgYiIgThPIXgDt2qPdey+TK0B599VQ2xM=,tag:FMhrsSkD+A0rKoZUIaz/EQ==,type:str]
wireguard:
    nano:
        private-key: ENC[AES256_GCM,data:/UTVt6RDG48SC8edQZJKbrQRl6ewRJ4fbWwlM2Zr48Sc8ThrUq7j2Fk/q38=,iv:tHRkCwzE2vSqTxIqlo0UBnoF1ipjzJQ52A0Sytf9xp0=,tag:LeNNRe80Qe1bx+EkkJWIXA==,type:str]
        public-key: ENC[AES256_GCM,data:RA6GbTY8C2vEZYkAYEGKJuCs8V4cJSEbly4lOaNk6cF6uxcuDGigo7Om8e0=,iv:t35l5AF2oU87nN9Ezeb92Rqu9WHfYCVY7ZTQnAt+EIg=,tag:zfrjExYv7XuXFQ9mrUEVPA==,type:str]
    micro:
        private-key: ENC[AES256_GCM,data:nt1Xt6q0UK4w9ZKZw20lKiAMdNWYaCz/WO9Ev9w1YyI+aB42cvOXqNFySxU=,iv:aOCLfzem8cX9OLPtlUKeh8HCzrAJAyLRJwtFXe+DKAM=,tag:sq82L4Gyny4bJtlsP7550g==,type:str]
        public-key: ENC[AES256_GCM,data:UUxp4cti4GCAvn7mvBuJRxJ/whvsc+TQGd1SLsbGFBluk6FDgfSymwzy7C0=,iv:rPfQMuHLP5v5G4oAhQA8LSKJdijst6IIvbPz9xMM9G0=,tag:B9y2505dazheDaBb9pqSfA==,type:str]
backup:
    credentials: ENC[AES256_GCM,data:SV/oahHqFEr1Vtz569W1VEM5VDtYjzd9ioVUoG84JqnWQX96xUSlisVSPYSXz3tcktCvxLHmpAxBLlyM0ZsGS2Urlh9CE7rVMI+g+YaFGt5xHBT5HI3R17TAau+1ftXmqYyfudv5ibAGIp2N8s8sx/4C6bWHCVQKT1CuxDWK+4cpWhA6Zdi3fKcFU9sx5ZKH0o1wSrQZEbXXTJTsQeSXzo74YX8AvCuqWFurAiHlSkVj6AnwUrggE7vucXQ2fXYn/tgY+ZhBUieKFxuE,iv:Xx83gX51/Bk/UuZ7cjw82kTenrmeK9D7VqLqcSE37Go=,tag:2o2emEpGfv8bPDeIVo1S5g==,type:str]
    repository: ENC[AES256_GCM,data:/LlPAZnIt0C1NCmkGQtLSzG5E+b8yvbRQUsrnyIWhdpRthj8F/5IOufTMpy5B77BEiMKEIq5Fu17zvYADuD/82gwtPEY3A+cYpLVjOtMFdmU3g==,iv:kunmtlNNnZA4h8jbuZFDXZ5eP0wXYb9Ohghweu8pHFA=,tag:YU3WlGATV2ngcGNaTZkf+w==,type:str]
    password: ENC[AES256_GCM,data:avEufKEp7dnb1yT2rw==,iv:XHin65zJhJ+7jP7gzjJFEmQ96xQgF3/7hfjU6BuN3/k=,tag:FpIdWCehH0e/E5sW4BWVEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18fmflp9w4lzh8e2gpxhzeu0n4vy769n3asfhj39tn3sn320zzdps7yz53w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aXFEWmlKbGhhMllhSTVm
            ajVncTlxTnZYZDhjYnEzaUYzSktVZFFOWWtFCnN4b0U4VjdSZGthQVpFZjlJR2h4
            VlpjdlZlZkRqZWhyM0QxQUgydVVMTEEKLS0tIEZsdVZtV1JvZkMxQzhSMG4xT282
            aUkzUThiUDJuUkNEOGZuSDQvZzM1dTAKGcrAAmi2DiIhwTGf5JUenGtod2wffFdh
            U/kx2MBpz5wn7XfnNjb6Ec7qMAnvce+huOL+yA9y97ooasYia2Da5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age196rtqfrvsu4x7e39aknntd7ne5fl20ggk3yuz2v0tm09wmavzeusj46fsm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqemxjbjhoejM5V3I3Sk11
            OVNxY3RpUDlHdzVUczFPVTlxSS9vZEIyUUhvCkJZM2l6TEpULzV6V3dzRjhvYVN6
            UmZmMk50UCtnclR4WUo3bEVjZmtwdlUKLS0tIEUza29ycnZLZmtlUHY1YkREU3RV
            NytNbTNseml1WldmaVdMTFdJdWJXdmsKC6Z9hB/2KwjCu2HaNvl79Qpj+jU0m6MH
            vFM2L62RNAE7VC1ZFhonzMcupS8gJWsSV9ObKm7Er8ueRdc8fifeyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e36nrp3jcjwdhvfsmva9rx04tp3p9y28pw6ukjtxjyssfwscqfxqzlfx5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dng2TTNCT3BMaTRWWDRh
            dUtDL0c0T3QzbFBxa2ZuM3RsR0dRazR5TnhJCnRRZmNrN2I0UktpNndPclNXU0dz
            SEt6cjV3SE5IajNLVENWelBycElQZHcKLS0tIFFFQ1hFbU8raFBxTUFsOWxqTFB2
            MFJaZ0xRWGFOVTdXajBWRWN6K1ZzRE0K3rebiK9B0sMIYd7Zu0lGyB2Mh+hEyx8N
            cpt4Awu0YmKQ405/b28pPev165Qkp2k0EPOlSXeRwJRxaoPzJMOK9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m43cprvuz5kdrla7lwsdlt324kys788n9g7lv4pzslvd4xvlt5gsjgm4q8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dzdRVEV0a1dYd0EraVQ0
            YUNnTE5WUW9WbmRKWFlMRDlvL29MKzVBeFZnCm9GM0lsYjFZYzVtUXlQL0pnRTJP
            NGFYdkZxVWtBWDZNV2NGQ29DMHhnWlkKLS0tIFFORzVOWGU0d2llTVlwS0dBb3V3
            SXJzRFQ3WXRkWDA1R3ZwVitkVE5CUW8Kb1LVDiHTGyzmAiSn6xtNV98Z+OwFoZQV
            91bJVP/O2VR6NjKlWe8NpIe8b2BqvujitxLGURIQt2UctzKIyohQzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T18:29:48Z"
    mac: ENC[AES256_GCM,data:7Z98Pc59yiAoY0e0iPvnTXQ7jq2c7C6n0SI/GVjghpvklv8hs85odopp3lxpRPKMyE8i6lduhVZ7xPUbiEG+RIr21vKdisH/MjdOb7D39mk2oURJKWVzqH2xjjzUOlgzsIR/ntGyFaIf93YbTce0FW6dyiiTycabNmBdddB55rg=,iv:BPtu8en7Z1l8xUVhNeAmMkseNULGGuYGWCpAdmqpPGY=,tag:M7JI65vH4T+g1igkacwD2A==,type:str]
    pgp:
        - created_at: "2025-03-09T16:35:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzBnNu2Md+DVARAAoJGmiUkJzLrLDH2hF8SfurDTJODYGB2ALcqC6itwBmTV
            dqNAqwtnDYp5lIiZeFUXBsArAu/ILhN0D2lMg142bCPwgOAeqZen4HO0ECKzAegb
            V/71RhgMBl+CRezv0xrBAY3hwW2xODAqJFgsyN3tKRcF4sh8BY8vw3UkYaLNYCJn
            XiTBbzAm6lnvMeFzuRns1HwEZPe/77VfSYoX0W1CmI9z5iE5rSarAiqkX1GLDn+l
            wR157EENvAzu4lPe6O1WVxc2lrvpegL9JMpK0SiIl7PgxXFuyPArWsvSOCTbbOBj
            WdvvUkBzjz8eX/fz1yXCcQrpLfwdX45arNBWJwWdI1Wd81mpIiqdUzDfJDLbfaYD
            KJHt59UaVwfnSBZ+OZyx/eo8U4j6LsL8NoW8CVYe1djs9wdEAUcnR0+WPzPQw94y
            oGNiaCsDJoS3KbIAWqtVUmIAXMYruba5WuGUURbnN2nB1OeCy+1aW3XbKaQ+oOBF
            R78kPjeFtuv6/QaLpxVnjqIsKOZdrF/8ELDSWNLdCtjBqlKq+QPv+Ij7iiKuEnGH
            vhoB82l1gX5Uib4MffewCcHP3wVqr7k1Ig9udJJEZi1dT1iCoPGCvUkzx9exfFJF
            4MeVbk7cYvYL4E1GoVMoGCNqy0bvOcRH4MC1gjJbdQUkmqsq9bSMb3bj0//xSzbS
            XgEYGmiBc5HeZcvpjNQUbvJr1bvlXk2/5RTWGuCkokw623WtOBe1SMQ09TVlN1w+
            QE6FBwAyishkf61fT1Yi0uGefmav7dUjjNJTq3wMUr6F+XILdnj7ijQJc9+0Al8=
            =2751
            -----END PGP MESSAGE-----
          fp: b7f7f218a0541d2a0bedbe8beb70fef3cdfc6e4f
    unencrypted_suffix: _unencrypted
    version: 3.8.1
