msmtp:
    password: ENC[AES256_GCM,data:S76Cp1qc/EKXlqQBFBWPtw==,iv:o4qCg+qRHrcvM99Ijysr9o/qoUdq+9vbKWI7bi7zg0w=,tag:JazB1ButYEvnnxGpmenhvw==,type:str]
irssi-nickserv: ENC[AES256_GCM,data:sWxgDbtwHcQ54EholpOqQHDv8Oc=,iv:5imtFQK/ZlBnnar/waWArYWcXeHKlHSy2Vbs2opnJHM=,tag:P7ix7GdK/DIrlpCjLz7IIA==,type:str]
openapi: ENC[AES256_GCM,data:CDbTW7DFfEvgCUHnreAfEYs1nJnC3eGNe9CIb/78BzlEk8C99dB33HB7OOA42KlG7UoR,iv:rPsO3QetQPhgYiIgThPIXgDt2qPdey+TK0B599VQ2xM=,tag:FMhrsSkD+A0rKoZUIaz/EQ==,type:str]
wireguard:
    nano:
        private-key: ENC[AES256_GCM,data:/UTVt6RDG48SC8edQZJKbrQRl6ewRJ4fbWwlM2Zr48Sc8ThrUq7j2Fk/q38=,iv:tHRkCwzE2vSqTxIqlo0UBnoF1ipjzJQ52A0Sytf9xp0=,tag:LeNNRe80Qe1bx+EkkJWIXA==,type:str]
        public-key: ENC[AES256_GCM,data:RA6GbTY8C2vEZYkAYEGKJuCs8V4cJSEbly4lOaNk6cF6uxcuDGigo7Om8e0=,iv:t35l5AF2oU87nN9Ezeb92Rqu9WHfYCVY7ZTQnAt+EIg=,tag:zfrjExYv7XuXFQ9mrUEVPA==,type:str]
    micro:
        private-key: ENC[AES256_GCM,data:nt1Xt6q0UK4w9ZKZw20lKiAMdNWYaCz/WO9Ev9w1YyI+aB42cvOXqNFySxU=,iv:aOCLfzem8cX9OLPtlUKeh8HCzrAJAyLRJwtFXe+DKAM=,tag:sq82L4Gyny4bJtlsP7550g==,type:str]
        public-key: ENC[AES256_GCM,data:UUxp4cti4GCAvn7mvBuJRxJ/whvsc+TQGd1SLsbGFBluk6FDgfSymwzy7C0=,iv:rPfQMuHLP5v5G4oAhQA8LSKJdijst6IIvbPz9xMM9G0=,tag:B9y2505dazheDaBb9pqSfA==,type:str]
backup:
    credentials: ENC[AES256_GCM,data:SV/oahHqFEr1Vtz569W1VEM5VDtYjzd9ioVUoG84JqnWQX96xUSlisVSPYSXz3tcktCvxLHmpAxBLlyM0ZsGS2Urlh9CE7rVMI+g+YaFGt5xHBT5HI3R17TAau+1ftXmqYyfudv5ibAGIp2N8s8sx/4C6bWHCVQKT1CuxDWK+4cpWhA6Zdi3fKcFU9sx5ZKH0o1wSrQZEbXXTJTsQeSXzo74YX8AvCuqWFurAiHlSkVj6AnwUrggE7vucXQ2fXYn/tgY+ZhBUieKFxuE,iv:Xx83gX51/Bk/UuZ7cjw82kTenrmeK9D7VqLqcSE37Go=,tag:2o2emEpGfv8bPDeIVo1S5g==,type:str]
    repository: ENC[AES256_GCM,data:/LlPAZnIt0C1NCmkGQtLSzG5E+b8yvbRQUsrnyIWhdpRthj8F/5IOufTMpy5B77BEiMKEIq5Fu17zvYADuD/82gwtPEY3A+cYpLVjOtMFdmU3g==,iv:kunmtlNNnZA4h8jbuZFDXZ5eP0wXYb9Ohghweu8pHFA=,tag:YU3WlGATV2ngcGNaTZkf+w==,type:str]
    password: ENC[AES256_GCM,data:avEufKEp7dnb1yT2rw==,iv:XHin65zJhJ+7jP7gzjJFEmQ96xQgF3/7hfjU6BuN3/k=,tag:FpIdWCehH0e/E5sW4BWVEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18fmflp9w4lzh8e2gpxhzeu0n4vy769n3asfhj39tn3sn320zzdps7yz53w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3anJaQW5FaE1mK0M3SkJr
            Qm02c1REY3JVSXp5MmVLTldpU21kaExwUFhJCmh6QzJrNTB6c2pmMUNTZkUwM0o3
            dTZFUkVQWEFqNXh1clV5TnpsNVJZekUKLS0tICtoUjY0S29KOXVhTEhJMjBGN1h5
            dkpsQ0poSmx6eE8xRzZXQ2Fmc0xlV1EKKsNHSmiZBlPfYdCcUhcm//1ARj/HoLUB
            a3jdYnYqgoZR19lGN6qLZtKmBq28OOG16+S0MSJrc93RnJS679D7eA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age196rtqfrvsu4x7e39aknntd7ne5fl20ggk3yuz2v0tm09wmavzeusj46fsm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZm1hakk4S0NPVXRnMEtQ
            ZjJkeHp4SUJiZ1dHNTVGS1AwU1E1VGdEc1JBCkNaakF5eGZFTmVDRyttWGJXWE9N
            amFHblNCR3Q3NVhvSDYzaWhjM1VsTmcKLS0tICtTY0lSbFVlU1FBajA1cngyeXBp
            MEd0emJtbkdZbVgyK0l4OUJkTEFUNnMKjo9Y0RL28Hq3U/R1VONqnAKD9EegDj5q
            nqHpMcLZpR9UyRdCTIXAFoARbPLoxYkUIprN4mG3fTJs0c4ByLacng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u9ug8zm5jkrz52np2jrmhuqehlzntpckkd843vvvex9uec2f29xs60yfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWHdRZ1N6UmV5MEJqMXI1
            S3RsQWkycWpoYVdxZTdPUUNMcGk4U2U5RmpvCnBLUUdqWmRCeDg5d2ZoSWU3NkF5
            MkNjM2picFl6d1Zub1FCamtqSVRuZTgKLS0tIE5icXZ0Mm5MbXRnaXdONE53VXhi
            MFVIWWptUG4xLzkyQnF2UmJTWE96bTQKndarFiHcbFjEGlatq6/EekvRZaE07hRy
            NmZYch2TGE9IXSJVcWfwroUPxsdL2ux0+RR5SDnIYx1Kl7VQTxJM1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T18:29:48Z"
    mac: ENC[AES256_GCM,data:7Z98Pc59yiAoY0e0iPvnTXQ7jq2c7C6n0SI/GVjghpvklv8hs85odopp3lxpRPKMyE8i6lduhVZ7xPUbiEG+RIr21vKdisH/MjdOb7D39mk2oURJKWVzqH2xjjzUOlgzsIR/ntGyFaIf93YbTce0FW6dyiiTycabNmBdddB55rg=,iv:BPtu8en7Z1l8xUVhNeAmMkseNULGGuYGWCpAdmqpPGY=,tag:M7JI65vH4T+g1igkacwD2A==,type:str]
    pgp:
        - created_at: "2023-04-06T21:00:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzBnNu2Md+DVAQ//VtCFjKIupL/gWddBsu5axyNLKUGABqIj1x2nfMSonMIf
            ZhINmb3vDTeu5Q6s0dkNds4IAB2GnBY8s/3CVTF7XLK1DsSjuoIPkfcjgMo2unSc
            sPPwIF2iLV2+Q/VT5ARoxbBk41GI3Ecx1BegafTqdwjjv/+4OWm8VWZkvzZsdtbV
            mEnABV/159MOqQ+6mBwxsplH1pHcQ68WtgiXOZDvVYvkp+34CD6zHE64y62ZgTQP
            pAuxMCWp2R98UThlyaSs8BunoH/8H49XdAVP1iU2lH+QGMn+Y50RKn7BM3f5A0hg
            61WZ2THA/U0QHPXs0Zhp9XlhdOdKwwTWsoKWcby8jnKOMcU5ku94SIaLWzuMqdvr
            KDH37M4uV39Fs4tavBglNoK5YUVobDRJ68BdhCLG7EUNUZT2rKI8xGCApJ+g5HHX
            2rFSWLd728eFAVdAttLKVziF6Wrx4jfzMvjmsEmdciQAQXDrQpQt0TKffWF2ErSO
            RcpAic/fWngx1BHN1BP86666cC6kM/xrxdYdtNGJPFQCKtfEwgpK6DJ6LvoE4Bxs
            4b429X765zmowlSInC7TiBoSMrbInhKX/bfyvbar9uKRqNRvXcKZ/1qmV46Q7X7U
            lNeUuER7JkiO/MVT8Qcgi3i+wg0bb48dQpFkngxkWoZdevzv9cEb/RAv1qCK1WXS
            XgGCLgr+F7Kd3kMonl+oyCXvRUjeYLJMIpXqQr9YBZqEeB2kRt0HMkfN1TS2yFdn
            RHzguGdHKugUhfBvkuxCxwByNIF1PdAaakrS5iuKaNVDQkzg/ckgQFoIkpdljwo=
            =qp77
            -----END PGP MESSAGE-----
          fp: b7f7f218a0541d2a0bedbe8beb70fef3cdfc6e4f
    unencrypted_suffix: _unencrypted
    version: 3.8.1
