msmtp:
    password: ENC[AES256_GCM,data:S76Cp1qc/EKXlqQBFBWPtw==,iv:o4qCg+qRHrcvM99Ijysr9o/qoUdq+9vbKWI7bi7zg0w=,tag:JazB1ButYEvnnxGpmenhvw==,type:str]
irssi-nickserv: ENC[AES256_GCM,data:sWxgDbtwHcQ54EholpOqQHDv8Oc=,iv:5imtFQK/ZlBnnar/waWArYWcXeHKlHSy2Vbs2opnJHM=,tag:P7ix7GdK/DIrlpCjLz7IIA==,type:str]
openapi: ENC[AES256_GCM,data:CDbTW7DFfEvgCUHnreAfEYs1nJnC3eGNe9CIb/78BzlEk8C99dB33HB7OOA42KlG7UoR,iv:rPsO3QetQPhgYiIgThPIXgDt2qPdey+TK0B599VQ2xM=,tag:FMhrsSkD+A0rKoZUIaz/EQ==,type:str]
wireguard:
    nano:
        private-key: ENC[AES256_GCM,data:/UTVt6RDG48SC8edQZJKbrQRl6ewRJ4fbWwlM2Zr48Sc8ThrUq7j2Fk/q38=,iv:tHRkCwzE2vSqTxIqlo0UBnoF1ipjzJQ52A0Sytf9xp0=,tag:LeNNRe80Qe1bx+EkkJWIXA==,type:str]
        public-key: ENC[AES256_GCM,data:RA6GbTY8C2vEZYkAYEGKJuCs8V4cJSEbly4lOaNk6cF6uxcuDGigo7Om8e0=,iv:t35l5AF2oU87nN9Ezeb92Rqu9WHfYCVY7ZTQnAt+EIg=,tag:zfrjExYv7XuXFQ9mrUEVPA==,type:str]
    micro:
        private-key: ENC[AES256_GCM,data:nt1Xt6q0UK4w9ZKZw20lKiAMdNWYaCz/WO9Ev9w1YyI+aB42cvOXqNFySxU=,iv:aOCLfzem8cX9OLPtlUKeh8HCzrAJAyLRJwtFXe+DKAM=,tag:sq82L4Gyny4bJtlsP7550g==,type:str]
        public-key: ENC[AES256_GCM,data:UUxp4cti4GCAvn7mvBuJRxJ/whvsc+TQGd1SLsbGFBluk6FDgfSymwzy7C0=,iv:rPfQMuHLP5v5G4oAhQA8LSKJdijst6IIvbPz9xMM9G0=,tag:B9y2505dazheDaBb9pqSfA==,type:str]
backup:
    credentials: ENC[AES256_GCM,data:SV/oahHqFEr1Vtz569W1VEM5VDtYjzd9ioVUoG84JqnWQX96xUSlisVSPYSXz3tcktCvxLHmpAxBLlyM0ZsGS2Urlh9CE7rVMI+g+YaFGt5xHBT5HI3R17TAau+1ftXmqYyfudv5ibAGIp2N8s8sx/4C6bWHCVQKT1CuxDWK+4cpWhA6Zdi3fKcFU9sx5ZKH0o1wSrQZEbXXTJTsQeSXzo74YX8AvCuqWFurAiHlSkVj6AnwUrggE7vucXQ2fXYn/tgY+ZhBUieKFxuE,iv:Xx83gX51/Bk/UuZ7cjw82kTenrmeK9D7VqLqcSE37Go=,tag:2o2emEpGfv8bPDeIVo1S5g==,type:str]
    repository: ENC[AES256_GCM,data:/LlPAZnIt0C1NCmkGQtLSzG5E+b8yvbRQUsrnyIWhdpRthj8F/5IOufTMpy5B77BEiMKEIq5Fu17zvYADuD/82gwtPEY3A+cYpLVjOtMFdmU3g==,iv:kunmtlNNnZA4h8jbuZFDXZ5eP0wXYb9Ohghweu8pHFA=,tag:YU3WlGATV2ngcGNaTZkf+w==,type:str]
    password: ENC[AES256_GCM,data:avEufKEp7dnb1yT2rw==,iv:XHin65zJhJ+7jP7gzjJFEmQ96xQgF3/7hfjU6BuN3/k=,tag:FpIdWCehH0e/E5sW4BWVEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18fmflp9w4lzh8e2gpxhzeu0n4vy769n3asfhj39tn3sn320zzdps7yz53w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMEFRdmpzbjVibWFxT2Vz
            L0loZjJlQ0wvbzU5YXlaeEEwQzZrbnZGTkQ0CnFtcTNYY25CVnlrOWo5aWVpYTlS
            Qkdob0FqVXRMZVJkUVVubWQzL2pMRzQKLS0tIEd4N2l4SmxIblQ4ckhjaWh4MzFZ
            YTR0UEFvVERvRUtZeDlzSzhjTXk5QUkK437ihWMa+PFeyFFAOmd07NKtu04hR2rL
            fBKbErU5RDkgZwWJFLpaanBt/BzgW4O+bibo1DD3Yv545wlnfmIZ3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age196rtqfrvsu4x7e39aknntd7ne5fl20ggk3yuz2v0tm09wmavzeusj46fsm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTWdSTVF0cEMyU1pQcW5p
            QktEQXlYbVkwc044RFJ4ZE8zdVNRTGZKRWxFCmM4N0dpR05hSytXTTBMYkRKWGEy
            TmE3T080QWdqS21Fa0VUbFNWQThaU1UKLS0tIDJZeWpRVE9OWWlzbkJhT2Y5L29B
            Rnk3c2dpbkY2eXNsd01HWGk3bUh6SDQKR3qJu3qjBZmmiQf7qNNMTqDqWruyTTAl
            XoT1EXbfj7SZj8dLu6DWmd9SpnfOoHeRGR5BRnJzWSY07jtJuBeYWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e36nrp3jcjwdhvfsmva9rx04tp3p9y28pw6ukjtxjyssfwscqfxqzlfx5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeEhWczdpV3NBVGFtWkNH
            U3JJaldzYVV3d2xyWHBCcWQ5dittZ0lTTDNZCiswUjJDcTJLSFNaaUorSEJSWTZj
            YUZYZXZBd0t2UlhadmhBZ0tXcTdFRVkKLS0tIHM5czNxbUNlTXVIM0NoWXBwT1g5
            VFRjU0cwTmNJd1RiQTQxTGhwbnhuMkkKZv5yixgFCqE1IvXBaOiyJJFRTSKSKxz8
            uxLXmeIamMMqGQoXuRilqxHQDNYFVq9mB7qYdwPOjGHo/zOGtrFpCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T18:29:48Z"
    mac: ENC[AES256_GCM,data:7Z98Pc59yiAoY0e0iPvnTXQ7jq2c7C6n0SI/GVjghpvklv8hs85odopp3lxpRPKMyE8i6lduhVZ7xPUbiEG+RIr21vKdisH/MjdOb7D39mk2oURJKWVzqH2xjjzUOlgzsIR/ntGyFaIf93YbTce0FW6dyiiTycabNmBdddB55rg=,iv:BPtu8en7Z1l8xUVhNeAmMkseNULGGuYGWCpAdmqpPGY=,tag:M7JI65vH4T+g1igkacwD2A==,type:str]
    pgp:
        - created_at: "2024-02-23T15:48:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzBnNu2Md+DVAQ/+LChI1pFw/beC7Zd2x48X2QdmZ7p/lL49VGAv4au2LNnF
            uJ4F9OZvOHYLZksbUhLndubax0t60wjdxGe1y64P7q0ap7xA4asfE0ehOfNBfveN
            /vbRLMy8/9RHWPlvmWRHZGQPhlysj8VGiQpK96n761UAD6Zy/Y6iXFQrfFROPS3n
            0set1nJKkYbLU4OXIoNbyM6UfllQZH5/vuty/eHThZZeeFqz4IYx2so3sDzdKLDA
            5UnqW7NE+tcoeISLD+AITfrugAo0PjcVypJ3d4TQE565Z+vVjnRPlddxbQrCePdd
            iSgC88lymh8TpwsAC9abSW94GntS7r/t7MP2gG19FQAt3jDEH2SQcn7Lt9yV0W/b
            WXA8WEsvk8wYPknLabGI9RZWiCB+CG1zwThvGLNQ6m41+mT2SZDhe4VI1zcok66G
            DLN51nd5H0ngB3s3Bt7YJyCUdl4nfbKRTDsnEnihSI9vr46d6GX1/RQyH6NW5RUD
            dkPFUkF9Bslx6oF/lM3BhQZI3zKT8NutTmmxpo5ueAzasfReB4f4l9ya/MXAmnOK
            oawoTnfBivwJobn/wTxwzWkFVx+8gFuJW8N/JtZG4mjxRS5vQnKndR/K5vzWVew4
            JwymMfTWW4FElGArH5wsJN8PliqOM0SjD5UUR6UHNhOHVhOWdWArEN/dN8gjzxDS
            XgHdxiDcqASH9DA5bU3dyECRj0C/MH7cf0kOgk9vhcbD4PclL8M5tJP+PTfeO6W2
            w6xF1Ylax+/Q/xNqDd8ZkU6Z5/avd4D/IwAsT9/Z4mSWgZSK2e+X2TzgZnXVosg=
            =G/Yl
            -----END PGP MESSAGE-----
          fp: b7f7f218a0541d2a0bedbe8beb70fef3cdfc6e4f
    unencrypted_suffix: _unencrypted
    version: 3.8.1
